apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: bulletinboard
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
