services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb-data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: ["--bind_ip_all"]
    networks:
      - app-network

  backend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./simple-fluid-page
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8081:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
