# Number of replicas for backend and frontend
replicaCount:
  backend: 1
  frontend: 1

# Backend configuration
backend:
  image:
    repository: 878311921064.dkr.ecr.eu-west-1.amazonaws.com/bulletinboard-backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"
    - name: MONGO_DB_NAME
      value: "BulletinBoardDb"
    - name: MONGO_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: backend-secret
          key: MONGO_CONNECTION_STRING

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Frontend configuration
frontend:
  image:
    repository: ghcr.io/luunomx/bulletinboard-frontend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  env:
    - name: VITE_API_BASE_URL
      value: "/api"

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi

# MongoDB connection info (used by backend-secret)
mongodb:
  username: username
  password: password
  serviceName: mongo-service
  database: BulletinBoardDb

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  host: bulletinboard.local
