apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/luunomx/kubernetes-solution.git
    targetRevision: main
    path: gitops/apps
    kustomize: {}            # <-- Added to enable Kustomize processing
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
