apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::878311921064:user/LuunomEC2Admin
      username: admin
      groups:
        - system:masters
