apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: bulletinboard
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 878311921064.dkr.ecr.eu-west-1.amazonaws.com/bulletinboard-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_DB_NAME
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_CONNECTION_STRING
