apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_CONNECTION_STRING: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.serviceName }}:27017/{{ .Values.mongodb.database }}"
