apiVersion: v1
kind: Secret
metadata:
  name: mongo-root-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongo-root-username: "{{ .Values.mongodb.username }}"
  mongo-root-password: "{{ .Values.mongodb.password }}"
